name: Bearer

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  policy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bearr Security
        uses: bearer/bearer-action@v2
      - name: Bearer Privacy
        uses: bearer/bearer-action@v2
        with:
          config-file: ./bearer-config.yml
          format: json